---
title: "Working File"
author: "Brandon Wong II"
date: "2026-02-28"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading Dataset


```{r}
library(igraph)
library(igraphdata)
library(Matrix)
library(dplyr)

# Margin helpers
def_marg <- c(5.1, 4.1, 4.1, 2.1)
no_marg  <- c(0, 0, 0, 0)

pa_road_edges <- read.table(
  "roadNet-PA.txt",
  comment.char = "#",
  col.names = c("from", "to")
)

pa_road_network <- graph_from_data_frame(pa_road_edges, directed=FALSE)

# Removes duplicate edges / self-loops
simple_pa_road <- simplify(pa_road_network)
summary(simple_pa_road)
```

```{r}
deg <- degree(simple_pa_road, mode="all")

degree_quantiles <- quantile(deg)
print(degree_quantiles)

# Calculate specific percentiles (e.g., top 1% or 0.1% hubs)
hub_percentiles <- quantile(deg, probs = c(0.9, 0.95, 0.99, 0.999))
print(hub_percentiles)
```


```{r}
articulation_points(simple_pa_road)
```

## Creating Subgraphs

```{r}
# Creating New Vertex Attribute
deg <- degree(simple_pa_road, mode="all")

V(simple_pa_road)$deg <- deg

sorted_deg <- sort(deg, decreasing = T, index.return = T)
highest_deg <- sorted_deg$x[0:10]
node_index <- sorted_deg$ix[0:10]

cbind(highest_deg, node_index)
```

```{r}
set.seed(043859)
neighborhood_subgraphs <- make_neighborhood_graph(simple_pa_road, order = 12, nodes = node_index[1:4], mode = "all")

sub1 <- neighborhood_subgraphs[[1]]
sub2 <- neighborhood_subgraphs[[2]]
sub3 <- neighborhood_subgraphs[[3]]
sub4 <- neighborhood_subgraphs[[4]]

plot(sub1,
     layout = layout_nicely,
     # === vertex properties 
     vertex.color = "yellow",
     vertex.frame.color = "black",
     vertex.shape = "square",
     vertex.size = 3,
     # === vertex label properties
     vertex.label = NA,
     # === edge properties
     edge.color = "black",
     edge.lty = 1,
     edge.width = 0.5,
     edge.arrow.size = 0.2,
)

plot(sub2,
     layout = layout_nicely,
     # === vertex properties 
     vertex.color = "yellow",
     vertex.frame.color = "black",
     vertex.shape = "square",
     vertex.size = 3,
     # === vertex label properties
     vertex.label = NA,
     # === edge properties
     edge.color = "black",
     edge.lty = 1,
     edge.width = 0.5,
     edge.arrow.size = 0.2,
)

plot(sub3,
     layout = layout_nicely,
     # === vertex properties 
     vertex.color = "yellow",
     vertex.frame.color = "black",
     vertex.shape = "square",
     vertex.size = 3,
     # === vertex label properties
     vertex.label = NA,
     # === edge properties
     edge.color = "black",
     edge.lty = 1,
     edge.width = 0.5,
     edge.arrow.size = 0.2,
)

plot(sub4,
     layout = layout_nicely,
     # === vertex properties 
     vertex.color = "yellow",
     vertex.frame.color = "black",
     vertex.shape = "square",
     vertex.size = 3,
     # === vertex label properties
     vertex.label = NA,
     # === edge properties
     edge.color = "black",
     edge.lty = 1,
     edge.width = 0.5,
     edge.arrow.size = 0.2,
)

random_nodes <- sample(V(mynetwork), 4)
```


```{r}
# Subgraph 1
# 1. Select the first starting node (highest degree)
sub1_deg <- degree(simple_pa_road, mode="all")
sub1_sorted_deg <- sort(sub1_deg, decreasing = T, index.return = T)

start_node_1 <- V(simple_pa_road)[sub1_sorted_deg$ix[1]]

# 2. Extract the neighborhood
# we use ego() to get the IDs directly
sub1_nodes <- ego(simple_pa_road, order = 12, nodes = start_node_1, mode = "all")[[1]]

# 3. Create the actual subgraph object for plotting/analysis
sub1 <- induced_subgraph(simple_pa_road, sub1_nodes)

plot(sub1,
     layout = layout_nicely,
     # === vertex properties 
     vertex.color = "yellow",
     vertex.frame.color = "black",
     vertex.shape = "square",
     vertex.size = 3,
     # === vertex label properties
     vertex.label = NA,
     # === edge properties
     edge.color = "black",
     edge.lty = 1,
     edge.width = 0.5,
     edge.arrow.size = 0.2,
)

# Remove these nodes from the main graph to create a "remaining" network
# We use the names/indices to delete them
remaining_network <- delete_vertices(simple_pa_road, sub1_nodes)


# Subgraph 2 
# Recalculate degrees on the REMAINING network to find the new "best" start node
sub2_deg <- degree(remaining_network)
sub2_sorted_deg <- sort(sub2_deg, decreasing = TRUE, index.return = TRUE)

# Select the new highest degree node from what's left
start_node_2 <- V(remaining_network)[sub2_sorted_deg$ix[1]]

# Extract the neighborhood from the remaining network
sub2_nodes <- ego(remaining_network, order = 12, nodes = start_node_2, mode = "all")[[1]]
sub2 <- induced_subgraph(remaining_network, sub2_nodes)

plot(sub2,
     layout = layout_nicely,
     # === vertex properties 
     vertex.color = "yellow",
     vertex.frame.color = "black",
     vertex.shape = "square",
     vertex.size = 3,
     # === vertex label properties
     vertex.label = NA,
     # === edge properties
     edge.color = "black",
     edge.lty = 1,
     edge.width = 0.5,
     edge.arrow.size = 0.2,
)

remaining_network1 <- delete_vertices(remaining_network, sub2_nodes)

# Subgraph 3
sub3_deg <- degree(remaining_network1)
sub3_sorted_deg <- sort(sub3_deg, decreasing = TRUE, index.return = TRUE)

start_node_3 <- V(remaining_network1)[sub3_sorted_deg$ix[1]]

sub3_nodes <- ego(remaining_network1, order = 12, nodes = start_node_3, mode = "all")[[1]]
sub3 <- induced_subgraph(remaining_network1, sub3_nodes)

plot(sub3,
     layout = layout_nicely,
     # === vertex properties 
     vertex.color = "yellow",
     vertex.frame.color = "black",
     vertex.shape = "square",
     vertex.size = 3,
     # === vertex label properties
     vertex.label = NA,
     # === edge properties
     edge.color = "black",
     edge.lty = 1,
     edge.width = 0.5,
     edge.arrow.size = 0.2,
)

remaining_network2 <- delete_vertices(remaining_network1, sub3_nodes)

# Subgraph 4 
sub4_deg <- degree(remaining_network2)
sub4_sorted_deg <- sort(sub4_deg, decreasing = TRUE, index.return = TRUE)

# Select the new highest degree node from what's left
start_node_4 <- V(remaining_network2)[sub4_sorted_deg$ix[1]]

sub4_nodes <- ego(remaining_network2, order = 12, nodes = start_node_4, mode = "all")[[1]]
sub4 <- induced_subgraph(remaining_network2, sub4_nodes)

plot(sub4,
     layout = layout_nicely,
     # === vertex properties 
     vertex.color = "yellow",
     vertex.frame.color = "black",
     vertex.shape = "square",
     vertex.size = 3,
     # === vertex label properties
     vertex.label = NA,
     # === edge properties
     edge.color = "black",
     edge.lty = 1,
     edge.width = 0.5,
     edge.arrow.size = 0.2,
)

remaining_network3 <- delete_vertices(remaining_network2, sub4_nodes)

# Subgraph 5 
sub5_deg <- degree(remaining_network3)
sub5_sorted_deg <- sort(sub5_deg, decreasing = TRUE, index.return = TRUE)

start_node_5 <- V(remaining_network3)[sub5_sorted_deg$ix[1]]

sub5_nodes <- ego(remaining_network3, order = 12, nodes = start_node_5, mode = "all")[[1]]
sub5 <- induced_subgraph(remaining_network3, sub5_nodes)

plot(sub5,
     layout = layout_nicely,
     # === vertex properties 
     vertex.color = "yellow",
     vertex.frame.color = "black",
     vertex.shape = "square",
     vertex.size = 3,
     # === vertex label properties
     vertex.label = NA,
     # === edge properties
     edge.color = "black",
     edge.lty = 1,
     edge.width = 0.5,
     edge.arrow.size = 0.2,
)

network_stats <- data.frame(
  Stage = c("Initial (Sub1)", "Iteration 2 (Sub2)", "Iteration 3 (Sub3)", "Iteration 4 (Sub4)", "Iteration 5 (Sub5)"),
  Available_Nodes = c(vcount(simple_pa_road), vcount(remaining_network), vcount(remaining_network1), 
                      vcount(remaining_network2), vcount(remaining_network3)),
  Available_Edges = c(ecount(simple_pa_road), ecount(remaining_network), ecount(remaining_network1), 
                      ecount(remaining_network2), ecount(remaining_network3)),
  Subgraph_Nodes = c(vcount(sub1), vcount(sub2), vcount(sub3), vcount(sub4), vcount(sub5)),
  Subgraph_Edges = c(ecount(sub1), ecount(sub2), ecount(sub3), ecount(sub4), ecount(sub5))
)

# Print the table to the console
print(network_stats)
```


```{r, fig.height=8, fig.width=8}
set.seed(894035)

large_subgraph <- make_neighborhood_graph(simple_pa_road, order = 40, nodes = sample(V(simple_pa_road), 1))[[1]]

large_sub1 <- induced.subgraph(large_subgraph, sample(V(large_subgraph), 200))

plot(large_sub1,
     # layout = layout_with_kk,
     # === vertex properties
     vertex.color = "hotpink",
     vertex.frame.color = "black",
     vertex.shape = "square",
     vertex.size = 3,
     # === vertex label properties
     vertex.label = NA,
     # vertex.label.cex = 0.3,
     # vertex.label.font = 2,
     # vertex.label.color = "red",
     # vertex.label.family = "Times",
     # vertex.label.distance = 3,
     # === edge properties
     edge.color = "red",
     edge.lty = 1,
     edge.width = 0.5,
     # edge.label = ...,
     # edge.label.family = ...,
     # edge.label.font = ...,
     # edge.label.cex = ...,
     # edge.curvature = ...,
     edge.arrow.size = 0.2
)
ecount(large_subgraph)
vcount(large_subgraph)
ecount(large_sub1)
vcount(large_sub1)
```

## Basic Summary Statistics / Metrics

```{r}
# Check for self-loops
sum(which_loop(simple_pa_road))

# Check for multiple edges between the same two nodes
sum(which_multiple(simple_pa_road))
```

```{r}
# Basic Summary Statistics

mean(degree(simple_pa_road)) # Average # of connections

summary(degree(simple_pa_road)) # Degree Distribution

vcount(simple_pa_road) # Number of Vertices (nodes)
ecount(simple_pa_road) # Number of Edges (connections)
```
```{r}
# ================  ~~ Descriptive Network Statistics (Metrics) ================

# Density 
graph.density(simple_pa_road)

# Reciprocity 
reciprocity(simple_pa_road)

# Transitivity 
transitivity(simple_pa_road)

# Reachability 
# average.path.length(simple_pa_road)

diameter(simple_pa_road, weights = NA)

#diameter(UKfaculty)

farthest_vertices(simple_pa_road)

#farthest_vertices(UKfaculty, , weights = NA)

# Connected components
is.connected(simple_pa_road, mode = "strong")
components(simple_pa_road, mode="strong")$no


# Articulation points
articulation.points(simple_pa_road)
```

```{r}
# Looking at Graph Attributes

graph_attr_names(simple_pa_road) # Whole network attributes
vertex_attr_names(simple_pa_road) # Vertex Attributes
edge_attr_names(simple_pa_road) # Edge Attributes
```



```{r}
# # Closeness Centrality

# cl <- closeness(simple_pa_road, mode="all", weights=NA) 
# 
# centr_clo(simple_pa_road, mode="all", normalized=T)
# 
# # arrange by closeness
# sort(cl, decreasing = T, index.return = T)
# 
# # uniform coloring
# V(simple_pa_road)$color <- "white"
# 
# #coloring 5 most central nodes
# # V(simple_pa_road)$color[V(simple_pa_road)[c(29, 37, 62, 52, 69)]] <- "#88398A"
# 
# # plot(simple_pa_road, 
# #      vertex.size=10,
# #      vertex.label.cex = 0.4,
# #      edge.arrow.size = 0.1)
# 


# # Betweeness Centrality

# btw <- betweenness(simple_pa_road, directed=T, weights=NA)
# 
# edge_betweenness(simple_pa_road, directed=T, weights=NA)
# 
# centr_betw(simple_pa_road, directed=T, normalized=T)
# 
# # sorting by betweenness 
# sort(btw, decreasing = T, index.return = T)
# 
# # V(simple_pa_road)$color[V(simple_pa_road)[c(62, 29, 37, 38, 52)]] <- "#88398A"
# 
# # plot(simple_pa_road, 
# #      vertex.size=10,
# #      vertex.label.cex = 0.4,
# #      edge.arrow.size = 0.1)
```




## Colors!
```{r}
# colors()
red_colors <- colors()[grep("red", colors())]
orange_colors <- colors()[grep("orange", colors())]
yellow_colors <- colors()[grep("yellow", colors())]
green_colors <- colors()[grep("green", colors())]
blue_colors <- colors()[grep("blue", colors())]
purple_colors <- colors()[grep("purple", colors())]
brown_colors <- colors()[grep(c("brown"), colors())]
pink_colors <- colors()[grep("pink", colors())]
white_colors <- colors()[grep("white", colors())]
black_colors <- colors()[grep("black", colors())]
light_colors <- colors()[grep("light", colors())]



color_plot <- function(my_colors) {
  # 2. Set up a blank plot area
  plot(NULL, xlim=c(0, 4), ylim=c(0, 5), xlab="", ylab="", xaxt="n", yaxt="n")

  # 3. Loop through and draw rectangles
  for(i in 1:length(red_colors)) {
    # Calculate position
    x_pos <- (i-1) %% 4
    y_pos <- 4 - floor((i-1) / 4)
  
    # Draw rectangle
    rect(x_pos, y_pos, x_pos+0.9, y_pos+0.8, col=my_colors[i], border="black")
  
    # Add label
    text(x_pos+0.45, y_pos+0.4, labels=my_colors[i], cex=0.7, col="black")
  }
}

color_plot(red_colors)
color_plot(orange_colors)
color_plot(yellow_colors)
color_plot(green_colors)
color_plot(blue_colors)
color_plot(purple_colors)
color_plot(brown_colors)
color_plot(pink_colors)
color_plot(white_colors)
color_plot(black_colors)
color_plot(light_colors)
```



